/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FurnituresRouteImport } from './routes/furnitures'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MaterialsMaterialIdRouteImport } from './routes/materials/$materialId'
import { Route as FurnituresAddRouteImport } from './routes/furnitures/add'
import { Route as authAuthRegisterRouteImport } from './routes/(auth)/auth/register'
import { Route as authAuthLoginRouteImport } from './routes/(auth)/auth/login'

const FurnituresRoute = FurnituresRouteImport.update({
  id: '/furnitures',
  path: '/furnitures',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsMaterialIdRoute = MaterialsMaterialIdRouteImport.update({
  id: '/materials/$materialId',
  path: '/materials/$materialId',
  getParentRoute: () => rootRouteImport,
} as any)
const FurnituresAddRoute = FurnituresAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => FurnituresRoute,
} as any)
const authAuthRegisterRoute = authAuthRegisterRouteImport.update({
  id: '/(auth)/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthLoginRoute = authAuthLoginRouteImport.update({
  id: '/(auth)/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/furnitures': typeof FurnituresRouteWithChildren
  '/furnitures/add': typeof FurnituresAddRoute
  '/materials/$materialId': typeof MaterialsMaterialIdRoute
  '/auth/login': typeof authAuthLoginRoute
  '/auth/register': typeof authAuthRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/furnitures': typeof FurnituresRouteWithChildren
  '/furnitures/add': typeof FurnituresAddRoute
  '/materials/$materialId': typeof MaterialsMaterialIdRoute
  '/auth/login': typeof authAuthLoginRoute
  '/auth/register': typeof authAuthRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/furnitures': typeof FurnituresRouteWithChildren
  '/furnitures/add': typeof FurnituresAddRoute
  '/materials/$materialId': typeof MaterialsMaterialIdRoute
  '/(auth)/auth/login': typeof authAuthLoginRoute
  '/(auth)/auth/register': typeof authAuthRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/furnitures'
    | '/furnitures/add'
    | '/materials/$materialId'
    | '/auth/login'
    | '/auth/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/furnitures'
    | '/furnitures/add'
    | '/materials/$materialId'
    | '/auth/login'
    | '/auth/register'
  id:
    | '__root__'
    | '/'
    | '/furnitures'
    | '/furnitures/add'
    | '/materials/$materialId'
    | '/(auth)/auth/login'
    | '/(auth)/auth/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FurnituresRoute: typeof FurnituresRouteWithChildren
  MaterialsMaterialIdRoute: typeof MaterialsMaterialIdRoute
  authAuthLoginRoute: typeof authAuthLoginRoute
  authAuthRegisterRoute: typeof authAuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/furnitures': {
      id: '/furnitures'
      path: '/furnitures'
      fullPath: '/furnitures'
      preLoaderRoute: typeof FurnituresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials/$materialId': {
      id: '/materials/$materialId'
      path: '/materials/$materialId'
      fullPath: '/materials/$materialId'
      preLoaderRoute: typeof MaterialsMaterialIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/furnitures/add': {
      id: '/furnitures/add'
      path: '/add'
      fullPath: '/furnitures/add'
      preLoaderRoute: typeof FurnituresAddRouteImport
      parentRoute: typeof FurnituresRoute
    }
    '/(auth)/auth/register': {
      id: '/(auth)/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof authAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/auth/login': {
      id: '/(auth)/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof authAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FurnituresRouteChildren {
  FurnituresAddRoute: typeof FurnituresAddRoute
}

const FurnituresRouteChildren: FurnituresRouteChildren = {
  FurnituresAddRoute: FurnituresAddRoute,
}

const FurnituresRouteWithChildren = FurnituresRoute._addFileChildren(
  FurnituresRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FurnituresRoute: FurnituresRouteWithChildren,
  MaterialsMaterialIdRoute: MaterialsMaterialIdRoute,
  authAuthLoginRoute: authAuthLoginRoute,
  authAuthRegisterRoute: authAuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
